# Generated by Django 5.1.4 on 2025-01-25 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_cart_product_cart_quantity_alter_cart_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
